apiVersion: skaffold/v3
kind: Config
build:
  artifacts:
    - image: logproxy
  # cluster: {}
  local:
    push: true
deploy:
  helm:
    releases:
      - name: k8s-log-proxy-dev
        chartPath: deploy/chart/k8s-log-proxy
        setValueTemplates:
          image.repository: "{{.IMAGE_REPO}}"
          image.tag: "{{.IMAGE_TAG}}@{{.IMAGE_DIGEST}}"
