apiVersion: v1
kind: ServiceAccount
metadata:
  name: log-reader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-pod-logs
subjects:
- kind: ServiceAccount
  name: log-reader
  apiGroup: ""
  namespace: default
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-log-proxy
spec:
  ports:
  - targetPort: http
    port: 80
    nodePort: 32032
  type: NodePort
  selector:
    app: k8s-log-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-log-proxy
spec:
  selector:
    matchLabels:
      app: k8s-log-proxy
  template:
    metadata:
      labels:
        app: k8s-log-proxy
    spec:
      serviceAccountName: log-reader
      securityContext:
        runAsNonRoot: true
      containers:
      - name: proxy
        image: k8s-log-proxy
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["all"]
