name: Goreleaser
on:
  push:
    branches:
      - "**"
    tags:
      - "*"
  pull_request:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: git fetch --force --tags
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        logout: true
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - uses: actions/setup-go@v4
      with:
        go-version: stable
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/adrianokf/k8s-log-proxy

    - uses: goreleaser/goreleaser-action@v4
      env:
        GORELEASER_ACTION: ${{ contains(github.ref, "refs/tags/") && 'release' || 'build' }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        distribution: goreleaser
        version: latest
        args: ${{ env.GORELEASER_ACTION }} --clean
