name: Release Helm charts
on:
  push:
    tags: ["*"]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
    - name: Package and upload Helm chart
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        CR_VERSION: "1.5.0"
      run: |
        curl -sSLo cr.tar.gz "https://github.com/helm/chart-releaser/releases/download/v${CR_VERSION}/chart-releaser_${CR_VERSION}_linux_amd64.tar.gz"
        tar -xzf cr.tar.gz cr
        rm cr.tar.gz

        owner=$(cut -d '/' -f 1 <<< "$GITHUB_REPOSITORY")
        repo=$(cut -d '/' -f 2 <<< "$GITHUB_REPOSITORY")

        # package chart
        ./cr package deploy/chart/$repo

        # upload chart to Github Releases
        ./cr upload \
            --owner "$owner" \
            --git-repo "$repo" \
            --release-name-template "{{ .Version }}"

        # update index and push to Github Pages
        git config user.email "$owner@users.noreply.github.com"
        git config user.name "$owner"
        ./cr index \
            --owner "$owner" \
            --git-repo "$repo" \
            --release-name-template "Helm chart v{{ .Version }}" \
            --index-path ./index.yaml \
            --charts-repo https://$owner.github.io/$repo \
            --push
      
